POST http://localhost:5000/insertDocument
content-type: application/json

{
  "title": "Hello World",
  "content": "This is a test asasdfdfaasdfsdfasdf!!adfs",
  "user": "4kang0624"
}

###
POST http://localhost:5000/getDocument
content-type: application/json

{
  "title": "Hello World",
  "version": 3
}

###
POST http://localhost:5000/getDocumentLog
content-type: application/json

{
  "title": "Hello World"
}